### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by josephgbr** [Buzztrax/buzzmachines#10]
Using the `--enable-debug` flag, compilation fails in Bigyo/FrequencyShifter displaying "error: invalid suffix on literal; C++11 requires a space between literal and string macro" four times.  See [build log](https://github.com/Buzztrax/buzzmachines/files/335525/buzzmachines-build.log.txt) and [config.log](https://github.com/Buzztrax/buzzmachines/files/335526/config.log.txt).

Without such flag, compilation still fails, now in FSM/ArpMan, displaying some more error message. See [build log](https://github.com/Buzztrax/buzzmachines/files/335533/buzzmachines-build.log.txt) and [config.log](https://github.com/Buzztrax/buzzmachines/files/335534/config.log.txt).

Environment: Arch Linux 64-bit, GCC 6.1.1

Please help?

**Comment by ensonic** [comment]
Thanks for reporting those. You are using a much never gcc than I have and many of the are super easy to fix. Can you try this and send pull requests?

**Comment by ensonic** [comment]
Fixed one of the as an example.

**Comment by josephgbr** [comment]
Your commit fixes Bigyo/FrequencyShifter and compilation with `--enable-debug` moves along.
However, compilation still fails in FSM/ArpMan. After some research, It seems ArpMan.ccp includes DSPChips.h, which (indirectly?) use `min` and `max` with different number of parameters required by GCC 6.1.1's headers `bits/stl_algobase.h`, `/bits/algorithmfwd.h` and `limits`.
Maybe ArpMan.ccp is using wrong min and max definitions? I notice that DSPChips.h includes windef.h, which defines min and max with adequate number of parameters, but Gedit's syntax highlighting warned me that the file windef.h was not found. Not sure whether it is relevant, though...

**Comment by ensonic** [comment]
I'll take a look. What you can do for now is to run ```make -k``` (keep going). Then you can fix the easy ones and leave the rest for me :).

**Comment by josephgbr** [comment]
You might see 4 commits above, but please ignore the first one. The last three commits fix some of the errors. I've got stuck in two errors: one is in FSM/ArpMan.cpp, as I mentioned above, and the other is in Geonik/DspClasses/Delay.h ("error: 'min' was not declared in this scope").  See full output with `-k` flag: [buzzmachines-build.log.txt](https://github.com/Buzztrax/buzzmachines/files/337919/buzzmachines-build.log.txt).

**Comment by ensonic** [comment]
I've fixed the min/max compile issues and updated the HACKING instructions. Could you try make -k again?

**Comment by josephgbr** [comment]
Nice! No error reported now. Thanks a lot for your support!
